"""Type stubs for the compiled `ocrus._native` module.

The runtime API users are expected to touch lives in `ocrus/__init__.py`; these are the
raw bindings it wraps.
"""

from pathlib import Path
from typing import Any, Literal

__version__: str
REC_MODEL_FILE: str
DICT_FILE: str

class OcrusError(Exception): ...
class ModelNotFoundError(OcrusError): ...
class ModelError(OcrusError): ...
class ImageError(OcrusError): ...
class ConfigError(OcrusError): ...

class BBox:
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def as_tuple(self) -> tuple[int, int, int, int]: ...

class RubyAnnotation:
    @property
    def ruby_text(self) -> str: ...
    @property
    def bbox(self) -> BBox: ...
    @property
    def confidence(self) -> float: ...

class TextLine:
    @property
    def text(self) -> str: ...
    @property
    def bbox(self) -> BBox: ...
    @property
    def confidence(self) -> float: ...
    @property
    def ruby(self) -> list[RubyAnnotation]: ...

class Page:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def lines(self) -> list[TextLine]: ...
    def text(self) -> str: ...

class OcrResult:
    @property
    def pages(self) -> list[Page]: ...
    def full_text(self) -> str: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...

class OcrEngine:
    def __init__(
        self,
        *,
        model_dir: Path | None = None,
        mode: Literal["auto", "fastest", "accurate"] = "auto",
        charset: Literal["full", "jis"] = "full",
        dict_path: Path | None = None,
        threads: int | None = None,
        ruby: bool = False,
        beam_width: int = 5,
        confidence_threshold: float = 0.5,
    ) -> None: ...
    @property
    def model_dir(self) -> Path: ...
    def recognize_path(self, path: Path) -> OcrResult: ...
    def recognize_bytes(self, data: bytes) -> OcrResult: ...
    def recognize_raw(
        self, data: bytes, width: int, height: int, channels: int = 1
    ) -> OcrResult: ...

def default_model_dir() -> Path: ...
def models_ready(model_dir: Path | None = None) -> bool: ...
